import { II18 } from './i18.model';

export const en: II18 = {
    login: 'login',
    register: 'register',
    sign_in: 'sign in',
    sign_out: 'sign out',
    app_title: 'modish panel',
    app_title_: 'app title',
    forgot_password: 'forgot password',
    msg: {
        ui: {
            action_succeeded: 'action succeeded',
            error_occurred: 'something went wrong', // error occurred
            error_occurred_retry_again: 'error occurred, please try again',
            no_network_connection:
                'error occurred, please check your network connection and try again',
            new_vesion_available_update:
                'new vesion of app is available, you can update it.',
            item_will_be_removed_continue: 'item will be removed continue?',
            file_could_not_be_uploaded: 'the file could not be uploaded.',
            file_could_not_be_uploaded_max_size_n:
                'the file could not be uploaded max size {0}.',
            profile_img_not_uploaded_max_size_n:
                'the file could not be uploaded, use only "image" with size less than "{0}"',
            one_img_upload_allowed_remove_existing_one:
                'one img upload allowed, remove existing one',
            login_again: 'login again',
            no_default_lang_create:
                'no default language found, please create one',
        },
        back: {},
    },
    validation: {
        min_length: 'min length {value} character',
        mobile_format: 'mobile format is not valid',
        smsCode_format: 'code is not valid.',
        confirm_password: 'confirm password not match password.',
        slug: 'slug not match slug pattern.',
        email_format: 'email format is not valid',
        phone_format: 'phone format is not valid',
        password_format: 'password format is incorrect',
        required_field: 'required field',
    },
    dashboard: 'dashboard',
    username: 'username',
    password: 'password',
    name: 'name',
    lastname: 'last name',
    phone: 'phone',
    address: 'address',
    mobile: 'mobile',
    email: 'email',
    confirm_password: 'confirm password',
    old_password: 'old password',
    new_password: 'new password',
    confirm_new_password: 'confirm new password',
    show_password: 'Show password',
    register_your_mobile_number: 'Register your mobile number',
    submit: 'submit',
    verification_code_sended_via_sms_submit_here:
        'verification code sended via sms, submit here.',
    verification_code: 'verification code',
    create_an_account: 'create an account',
    send_again: 'send again',
    send_again_activationCode: 'send again activation code',
    in: 'in',
    second: 'second',
    search: 'search',
    home: 'home',
    library: 'library',
    more: 'more',
    loading_with_dots: 'loading...',
    retry: 'retry',
    title: 'title',
    // return: 'return',
    reset_password: 'reset password',
    log_out: 'log out',
    sync: 'sync',
    syncing: 'syncing',
    syncing_with_dots: 'syncing...',
    last_synced_on: 'last synced on',
    settings: 'settings',
    info: 'info',
    length: 'Length',
    pages: 'pages',
    description: 'description',
    follow: 'follow',
    unfollow: 'unfollow',
    see_more: 'see more',
    see_less: 'see less',
    format: 'format',
    helpful: 'helpful',
    report: 'report',
    all: 'all',
    of: 'of',
    from: 'from',
    to: 'to',
    previous: 'previous',
    next: 'next',
    no_item_found: 'no item found',
    was: 'was',
    by: 'by',
    load_more: 'load more',
    remove: 'remove',
    minute: 'minute',
    hour: 'hour',
    close: 'close',
    app_info: 'app info',
    version: 'version',
    version_mode: 'version mode',
    trial_mode: 'trial mode',
    trial: 'trial',
    update: 'update',
    shopping_cart: 'shopping cart',
    buy: 'buy',
    price: 'price',
    total_price: 'total price',
    recalculate: 'recalculate',
    cancel: 'cancel',
    ok: 'ok',
    create: 'create',
    save_and_new: 'Save and New',
    rename: 'rename',
    download: 'download',
    downloading: 'downloading',
    add: 'add',
    selected: 'selected',
    select_all: 'select all',
    deselect_all: 'deselect all',
    sales_id: 'Sales ID',
    profile: 'profile',
    profile_image: 'profile image',
    exist_in_library: 'exist in library',
    preview: 'preview',
    refund_amount: 'refund amount',
    vendor_name: 'vendor name',
    refund_type: 'refund type',
    drag_and_drop: 'drag and drop',
    choose_image: 'choose image',
    goto: 'go to',
    go: 'go',
    page_not_found: 'page not found',
    detail: 'detail',
    count: 'count',
    unit_price: 'unit price',
    type: 'type',
    text_size: 'text size',
    theme: 'theme',
    font: 'font',
    font_obj: {
        nunito: 'nunito',
    },
    increase_credit: 'increase credit',
    increase_your_account: 'increase your account',
    wrong_price: 'wrong_price',
    payment: 'payment',
    existing_credit: 'existing credit',
    change_password: 'change password',
    storage: 'storage',
    state: 'state',
    confirm: 'confirm',
    clear: 'clear',
    unknown: 'unknown',
    operating_system: 'operating system',
    browser: 'browser',
    device: 'device',
    zoom: 'zoom',
    reload_app: 'reload application',
    compatible_browsers: 'compatible browsers',
    app_compatible_browsers_:
        'All Desktop devices or Android devices: "Chrome browser"; IOS devices: "Safari browser".',

    person: 'person',
    person_manage: 'person manage',
    person_create: 'person create',
    person_update: 'person update',
    person_copy: 'person copy',

    stateForm: 'stateForm',
    copy: 'copy ',
    save: 'save',
    reset: 'reset',
    status: 'status',
    row: 'row',
    number: 'number',
    available: 'available',
    unavailable: 'unavailable',
    edit: 'edit',
    back: 'back',
    new_email: 'new email',
    next_Step: 'next step',
    prev_Step: 'prev step',
    reset_email: 'reset email',
    reset_phone: 'reset phone',
    new_phone: 'new phone',
    on: 'on',
    off: 'off',
    actions: 'action',
    resume: 'resume',
    active: 'active',
    inactive: 'inactive',
    size: 'size',
    logo: 'logo',
    date: 'date',
    and: 'and',
    amount: 'amount',
    months: 'months',
    value: 'value',

    language: 'language',
    language_manage: 'language',
    language_create: 'create language',
    language_update: 'update language',
    language_copy: 'copy language',
    language_view: 'view language',

    view: 'view',
    reload: 'reload',
    set_as_default: 'set as default',
    direction: 'direction',
    rtl: 'rtl',
    ltr: 'ltr',
    goto_update: 'go to update',

    brand: 'brand',
    brand_manage: 'brand',
    brand_create: 'create brand',
    brand_update: 'update brand',
    brand_copy: 'copy brand',
    brand_view: 'view brand',

    category: 'category',
    category_manage: 'category',
    category_create: 'create category',
    category_update: 'update category',
    category_copy: 'copy category',
    category_view: 'view category',

    country: 'country',
    country_manage: 'country',
    country_create: 'create country',
    country_update: 'update country',
    country_copy: 'copy country',
    country_view: 'view country',

    store: 'store',
    store_manage: 'store',
    store_create: 'create store',
    store_update: 'update store',
    store_copy: 'copy store',
    store_view: 'view store',

    show_more: 'show more',
    show_less: 'show less',

    vendor: 'vendor',

    parent: 'parent',
    image: 'image',
    choose_language: 'choose language',
    other_languages: 'other languages',

    currency: 'currency',
    code: 'code',
    currencySymbol: 'currencySymbol',

    area: 'area',
    area_manage: 'area',
    area_create: 'create area',
    area_update: 'update area',
    area_copy: 'copy area',
    area_view: 'view area',

    warehouse: 'warehouse',
    warehouse_manage: 'warehouse',
    warehouse_create: 'create warehouse',
    warehouse_update: 'update warehouse',
    warehouse_copy: 'copy warehouse',
    warehouse_view: 'view warehouse',

    variation: 'variation',
    variation_manage: 'variation',
    variation_create: 'create variation',
    variation_update: 'update variation',
    variation_copy: 'copy variation',
    variation_view: 'view variation',

    item: 'item',
    items: 'items',

    attribute: 'attribute',
    attribute_manage: 'attribute',
    attribute_create: 'create attribute',
    attribute_update: 'update attribute',
    attribute_copy: 'copy attribute',
    attribute_view: 'view attribute',

    product: 'product',
    product_manage: 'product',
    product_create: 'create product',
    product_update: 'update product',
    product_copy: 'copy product',
    product_view: 'view product',

    slug: 'slug',
    generate_Sku: 'generate sku',
    get_sku_list: 'get sku list',

    user: 'user',
    user_manage: 'user',
    user_create: 'create user',
    user_update: 'update user',
    user_copy: 'copy user',
    user_view: 'view user',

    refund: 'refund',
    refund_manage: 'refund',
    refund_create: 'create refund',
    refund_update: 'update refund',
    refund_copy: 'copy refund',
    refund_view: 'view refund',

    customer: 'customer',

    gender: 'gender',

    variation_type: {
        STRING: 'string',
        NUMBER: 'number',
        COLOR: 'color',
        SIZE: 'size',
    },

    gender_type: {
        male: 'male',
        female: 'female',
        other: 'other',
    },

    order: 'order',
    order_manage: 'order',
    order_create: 'create order',
    order_update: 'update order',
    order_copy: 'copy order',
    order_view: 'view order',

    tag: 'tag',
    tag_manage: 'tag',
    tag_create: 'create tag',
    tag_update: 'update tag',
    tag_copy: 'copy tag',
    tag_view: 'view tag',

    coupon: 'coupon',
    coupon_manage: 'coupon',
    coupon_create: 'create coupon',
    coupon_update: 'update coupon',
    coupon_copy: 'copy coupon',
    coupon_view: 'view coupon',

    badge: 'badge',
    badge_manage: 'badge',
    badge_create: 'create badge',
    badge_update: 'update badge',
    badge_copy: 'copy badge',
    badge_view: 'view badge',

    docAccount: 'docAccount',
    docAccount_manage: 'docAccount',
    docAccount_create: 'create docAccount',
    docAccount_update: 'update docAccount',
    docAccount_copy: 'copy docAccount',
    docAccount_view: 'view docAccount',

    return: 'return',
    return_manage: 'return',
    return_create: 'create return',
    return_update: 'update return',
    return_copy: 'copy return',
    return_view: 'view return',

    purshase: 'purshase',
    purshase_manage: 'purshase',
    purshase_create: 'create purshase',
    purshase_update: 'update purshase',
    purshase_copy: 'copy purshase',
    purshase_view: 'view purshase',

    purchaseReturn: 'purchaseReturn',
    purchaseReturn_manage: 'purchaseReturn',
    purchaseReturn_create: 'create purchaseReturn',
    purchaseReturn_update: 'update purchaseReturn',
    purchaseReturn_copy: 'copy purchaseReturn',
    purchaseReturn_view: 'view purchaseReturn',

    contact: 'contact',
    contact_manage: 'contact',
    contact_create: 'create contact',
    contact_update: 'update contact',
    contact_copy: 'copy contact',
    contact_view: 'view contact',

    adjustment: 'adjustment',
    adjustment_manage: 'adjustment',
    adjustment_create: 'create adjustment',
    adjustment_update: 'update adjustment',
    adjustment_copy: 'copy adjustment',
    adjustment_view: 'view adjustment',

    purchaseOrder: 'purchaseOrder',
    purchaseOrder_manage: 'purchaseOrder',
    purchaseOrder_create: 'create purchaseOrder',
    purchaseOrder_update: 'update purchaseOrder',
    purchaseOrder_copy: 'copy purchaseOrder',
    purchaseOrder_view: 'view purchaseOrder',
};
