import { II18 } from './i18.model';

export const en: II18 = {
    login: 'login',
    register: 'register',
    sign_in: 'sign in',
    sign_out: 'sign out',
    app_title: 'Delta Avaran Vision',
    app_title_: 'app title',
    forgot_password: 'forgot password',
    page_not_found: 'Page not found!',
    home: 'home',
    products: 'products',
    about_us: 'about us',
    contact: 'contact',
    company: 'company',
    customers: 'customers',
    packing: 'packing',
    spare_car_for_cars: 'spare parts for cars',
    cellophane: 'cellophane',
    bag: 'bag',
    shrink: 'shrink',
    seat_cover: 'seat cover',
    feethold: 'feethold',
    steering_wheel_cover: 'steering wheel cover',
    painting_promask: 'painting promask',
    fender_cover: 'fender cover',
    english: 'english',
    persian: 'فارسی',
    change_language: 'تغییر زبان',
    open: 'open',
    close: 'close',
    telegram: 'telegram',
    whatsapp: 'whatsapp',
    instagram: 'instagram',
    menu: 'menu',
    send_nationwide: 'send nationwide',
    originality_of_goods: 'originality of goods',
    advice_on_buying: 'advice on buying',
    quality: 'quality',
    commercial_contract: 'commercial contract',
    text: {
        about_our_company: 'about our company',
        contact_info: 'contact info',
        footer_text:
            'Delta Avaran Vision Company started its activities in 2006 with the production and import of industrial equipment related to the automotive and rail industriesand has continued to grow successfully.',
        company_address:
            'Tehran - Saadat Abad - Above Bostan Square - Corner of E 12th Aseman St - No. 72 - Second Floor',
        company_tel: '+(21) 22355222-22355227',
        our_custumer: 'our customers',
        contact_us: 'contact us',
        address: 'address',
        company_brand: 'DELTA AVARAN VISION',
        about_us_text_1:
            'Delta Avaran Vision Company started its activities in 2006 with the production and import of industrial equipment related to the automotive and rail industries and has continued to grow successfully.',
        about_us_text_2:
            "Since the inception of the company, much of Iran's automotive demand has been covered by this complex. DELTA AVARAN VISION has, in line with its strategic plans, obtained exclusive representation of non-Iranian companies operating in the field.",
        about_us_text_3:
            "Also the company with many years of experience in the production, sales and export of polymer products, paper and ... used in the automotive, repair, printing and packaging, cosmetics, HSE, food and beverage industries and ... . In addition to its special position in the domestic market, the company's products have made their way to foreign markets by exporting to over 18 countries. In this way, we are proud to have played a significant part in introducing the country's industry to international markets, relying on local and domestic capabilities. The company's products with the latest technology and formulation and with the use of fully automatic devices have paved the way in domestic and foreign markets.",
        copy_right: 'All rights reserved by Delta Avaran Vision',
    },
};
